version: '3.5'
services:
  app:
    container_name: mobile
    build: .
    ports:
      - 8081:8080
      - 3001:3000
    volumes:
      - .:/smi-mobile
      - yarn_cache:/smi-mobile/node_modules
    entrypoint: ["sh", "./scripts/start.sh"]
        
volumes:
  yarn_cache:
